from django.urls import path, re_path

from .views import *
from .views.media_access import LojaLogoView

urlpatterns = [
    path(
        '',
        HomeLojaView.as_view(),
        name='home_loja'
    ),
    path(
        'logo/',
        LojaLogoView.as_view(),
        name='logo_loja'
    ),
    path(
        'login/',
        LoginUsuarioLojaView.as_view(),
        name='login_loja'
    ),
    path(
        'editar_usuario/',
        UpdateUsuarioLojaView.as_view(),
        name='editar_usuario_loja',
    ),
    path(
        'logout/',
        LogoutUsuarioLojaView.as_view(),
        name='logout_loja'
    ),
    path(
        'editar_senha/',
        PasswordChangeUsuarioLojaView.as_view(),
        name='editar_senha_loja',
    ),
    path(
        'gerir_funcionarios/funcionarios/',
        ListFuncionariosView.as_view(),
        name='list_funcionarios'
    ),
    path(
        'gerir_funcionarios/funcionarios/funcionario_detail/<int:pk>/',
        CardFuncionarioView.as_view(),
        name='funcionario_detail'
    ),
    path(
        'gerir_funcionarios/funcionarios/criar_funcionario/',
        CriarFuncionarioView.as_view(),
        name='criar_funcionario'
    ),
    path(
        'gerir_funcionarios/funcionarios/desativar_funcionario/',
        DesativarFuncionarioView.as_view(),
        name='desativar_funcionario'
    ),
    path(
        'gerir_funcionarios/funcionarios/reativar_funcionario/',
        ReativarFuncionarioView.as_view(),
        name='reativar_funcionario'
    ),
    path(
        'gerir_funcionarios/funcionarios/adicionar_papel/<int:group>/<int:funcionario>/',
        AdicionarPapelFuncionarioView.as_view(),
        name='adicionar_papel'
    ),
    path(
        'gerir_funcionarios/funcionarios/remover_papel/<int:group>/<int:funcionario>/',
        RemoverPapelFuncionarioView.as_view(),
        name='remover_papel'
    ),
    path(
        'gerir_funcionarios/funcionarios/adicionar_papel/',
        AdicionarPapelFuncionarioView.as_view(),
        name='adicionar_papel'
    ),
    path(
        'gerir_funcionarios/funcionarios/remover_papel/',
        RemoverPapelFuncionarioView.as_view(),
        name='remover_papel'
    ),
    path(
        'gerir_funcionarios/',
        GestaoFuncionariosView.as_view(),
        name='gerir_funcionarios'
    ),
    path(
        'gerir_vendedores/vendedores/',
        ListVendedoresView.as_view(),
        name='list_vendedores'
    ),
    path(
        'gerir_vendedores/vendedores/vendedor_detail/<int:pk>/',
        CardVendedorView.as_view(),
        name='vendedor_detail'
    ),
    path(
        'gerir_vendedores/vendedores/alterar_comissao/',
        AlterarComissaoVendedorView.as_view(),
        name='alterar_comissao'
    ),
    path(
        'gerir_vendedores/',
        GestaoVendedoresView.as_view(),
        name='gerir_vendedores'
    ),
    path(
        'oferta_produtos/',
        GestaoOfertaProdutoListView.as_view(),
        name='gerir_oferta_produtos',
    ),
    path(
        'estoque_de_produtos/',
        GestaoEstoqueDeProdutosListView.as_view(),
        name='gestao_estoque_de_produtos',
    ),
    path(
        'produto/<int:produto_pk>/criar_produto_por_lote/',
        CriarProdutoPorLoteView.as_view(),
        name='criar_produto_por_lote',
    ),
    path(
        'produto/<int:produto_pk>/editar_lote/<int:pk>/',
        UpdateProdutoPorLoteView.as_view(),
        name='editar_produto_por_lote',
    ),
    path(
        'produto/<int:produto_pk>/lotes/',
        ListProdutosPorLoteView.as_view(),
        name='list_produtos_por_lote',
    ),
    path(
        'produto/<int:produto_pk>/lote_detail/<int:pk>/',
        CardProdutoPorLoteView.as_view(),
        name='produto_por_lote_detail',
    ),
    path(
        'produto/<int:produto_pk>/deletar_lote/<int:pk>/',
        DeleteProdutoPorLoteView.as_view(),
        name='delete_produto_por_lote',
    ),
    path(
        'produto/<int:produto_pk>/',
        GestaoProdutosPorLoteView.as_view(),
        name='gestao_produtos_por_lote',
    ),
    path(
        'estoque_de_produtos/produtos/',
        ListProdutosView.as_view(),
        name='list_produtos_estoque',
    ),
    path(
        'estoque_de_produtos/produto_detail/<int:pk>/',
        CardProdutoView.as_view(),
        name='produto_estoque_detail',
    ),
    path(
        'estoque_de_produtos/produto_detail_edit/<int:pk>/',
        CardProdutoEditView.as_view(),
        name='produto_estoque_detail_edit',
    ),
    path(
        'estoque_de_produtos/criar_produto/',
        CriarProdutoView.as_view(),
        name='criar_produto_estoque',
    ),
    path(
        'estoque_de_produtos/editar_produto/<int:pk>/',
        UpdateProdutoView.as_view(),
        name='editar_produto_estoque',
    ),
    path(
        'estoque_de_produtos/',
        GestaoProdutosEstoqueView.as_view(),
        name='gerir_produtos_estoque',
    ),
    path(
        'promocoes_produto/<int:pk>/',
        GestaoPromocoesProdutoCRUDView.as_view(),
        name='gerir_promocoes_produto',
    ),
    path(
        'produtos_promocao/<int:pk>/',
        GestaoProdutosPromocaoCRUDView.as_view(),
        name='gerir_produtos_promocao',
    ),
    re_path(
        r'^promocoes/(?P<pk>\d+)?/?$',
        GestaoPromocoesCRUDListView.as_view(),
        name='gerir_promocoes',
    ),
    path(
        'caixas/',
        EstadoCaixaListView.as_view(),
        name='estado_caixa',
    ),
    path(
        'gestao-caixas/',
        GestaoCaixaCRUDListView.as_view(),
        name='gestao_caixas',
    ),
    path(
        'venda/',
        EfetuarVendaView.as_view(),
        name='efetuar_venda',
    ),
]
