from django.urls import path

from .views import *

urlpatterns = [
    path(
        '',
        HomeLojaView.as_view(),
        name='home_loja'
    ),
    path(
        'login/',
        LoginUsuarioLojaView.as_view(),
        name='login_loja'
    ),
    path(
        'editar_usuario/',
        UpdateUsuarioLojaView.as_view(),
        name='editar_usuario_loja',
    ),
    path(
        'logout/',
        LogoutUsuarioLojaView.as_view(),
        name='logout_loja'
    ),
    path(
        'editar_senha/',
        PasswordChangeUsuarioLojaView.as_view(),
        name='editar_senha_loja',
    ),
    path(
        'gerir_funcionarios/funcionarios/',
        ListFuncionariosView.as_view(),
        name='list_funcionarios'
    ),
    path(
        'gerir_funcionarios/funcionarios/funcionario_detail/<int:pk>/',
        CardFuncionarioView.as_view(),
        name='funcionario_detail'
    ),
    path(
        'gerir_funcionarios/funcionarios/criar_funcionario/',
        CriarFuncionarioView.as_view(),
        name='criar_funcionario'
    ),
    path(
        'gerir_funcionarios/funcionarios/desativar_funcionario/',
        DesativarFuncionarioView.as_view(),
        name='desativar_funcionario'
    ),
    path(
        'gerir_funcionarios/funcionarios/reativar_funcionario/',
        ReativarFuncionarioView.as_view(),
        name='reativar_funcionario'
    ),
    path(
        'gerir_funcionarios/funcionarios/adicionar_papel/<int:group>/<int:funcionario>/',
        AdicionarPapelFuncionarioView.as_view(),
        name='adicionar_papel'
    ),
    path(
        'gerir_funcionarios/funcionarios/remover_papel/<int:group>/<int:funcionario>/',
        RemoverPapelFuncionarioView.as_view(),
        name='remover_papel'
    ),
    path(
        'gerir_funcionarios/funcionarios/adicionar_papel/',
        AdicionarPapelFuncionarioView.as_view(),
        name='adicionar_papel'
    ),
    path(
        'gerir_funcionarios/funcionarios/remover_papel/',
        RemoverPapelFuncionarioView.as_view(),
        name='remover_papel'
    ),
    path(
        'gerir_funcionarios/',
        GestaoFuncionariosView.as_view(),
        name='gerir_funcionarios'
    ),
]
