from django.urls import path, re_path
from django.views.generic import TemplateView

from .views import *

urlpatterns = [
    path(
        '',
        TemplateView.as_view(template_name='home_contratacao.html'),
        name='home_contratacao',
    ),
    path(
        'criar_usuario/',
        CreateUsuarioContratacaoView.as_view(),
        name='criar_usuario_contratacao',
    ),
    path(
        'login/',
        LoginUsuarioContratacaoView.as_view(),
        name='login_contratacao'
    ),
    path(
        'editar_usuario/',
        UpdateUsuarioContratacaoView.as_view(),
        name='editar_usuario_contratacao',
    ),
    path(
        'editar_senha/',
        PasswordChangeUsuarioContratacaoView.as_view(),
        name='editar_senha_contratacao'
    ),
    path(
        'logout/',
        LogoutUsuarioContratacaoView.as_view(),
        name='logout_contratacao'
    ),
    path(
        'contratos/',
        GestaoContratoCRUDListView.as_view(),
        name='gestao_contrato'
    ),
    path(
        'contratos_disponiveis/',
        ContratosDisponiveisCRUDView.as_view(),
        name='contratos_disponiveis',
    ),
    re_path(
        r'^contratos(/(?P<pk>\d+))?/$',
        GestaoContratoCRUDListView.as_view(),
        name='gestao_contrato',
    ),
    path(
        'visualizar_contrato_assinado/',
        ContratoAssinadoView.as_view(),
        name='visualizar_contrato_assinado'
    ),
    path(
        'cancelar_contrato/',
        CancelarContratoView.as_view(),
        name='cancelar_contrato'
    ),
    path(
        'dados_loja/',
        DadosLojaView.as_view(),
        name='dados_loja'
    ),
    path(
        'editar_dados_loja/',
        EditarDadosLojaView.as_view(),
        name='editar_dados_loja'
    ),
    path(
        'criar_admin/',
        CriarAdminLojaView.as_view(),
        name='criar_admin'
    ),
    path(
        'admin_list/',
        ListAdminView.as_view(),
        name='admin_list'
    ),
    path(
        'admin_detail/<int:pk>/',
        AdminCardView.as_view(),
        name='admin_detail'
    ),
    path(
        'deactivate_funcionario/',
        DesativarFuncionarioView.as_view(),
        name='deactivate_funcionario'
    ),
    path(
        'reactivate_funcionario/',
        ReativarUsuario.as_view(),
        name='reactivate_funcionario'
    ),
    path(
        'add_papel/<int:group>/<int:funcionario>/',
        AddFuncionarioGroupView.as_view(),
        name='add_papel'
    ),
    path(
        'remove_papel/<int:group>/<int:funcionario>/',
        RemoveFuncionarioGroupView.as_view(),
        name='remove_papel'
    ),
    path(
        'add_papel/',
        AddFuncionarioGroupView.as_view(),
        name='add_papel'
    ),
    path(
        'remove_papel/',
        RemoveFuncionarioGroupView.as_view(),
        name='remove_papel'
    ),
    path(
        'change_is_admin/',
        ChangeIsAdmin.as_view(),
        name='change_is_admin'
    ),
    path(
        'minha_loja/',
        InformacoesLojaView.as_view(),
        name='informacoes_loja'
    ),
]
