from django.urls import path, re_path
from django.views.generic import TemplateView

from .views import *

urlpatterns = [
    path(
        '',
        TemplateView.as_view(template_name='home_contratacao.html'),
        name='home_contratacao',
    ),
    path(
        'criar_usuario/',
        CreateUsuarioContratacaoView.as_view(),
        name='criar_usuario_contratacao',
    ),
    path(
        'login/',
        LoginUsuarioContratacaoView.as_view(),
        name='login_contratacao'
    ),
    path(
        'editar_usuario/',
        UpdateUsuarioContratacaoView.as_view(),
        name='editar_usuario_contratacao',
    ),
    path(
        'editar_senha/',
        PasswordChangeUsuarioContratacaoView.as_view(),
        name='editar_senha_contratacao'
    ),
    path(
        'logout/',
        LogoutUsuarioContratacaoView.as_view(),
        name='logout_contratacao'
    ),
    path(
        'contratos/',
        GestaoContratoCRUDListView.as_view(),
        name='gestao_contrato'
    ),
    path(
        'contratos_disponiveis/',
        ContratosDisponiveisCRUDView.as_view(),
        name='contratos_disponiveis',
    ),
    re_path(
        r'^contratos(/(?P<pk>\d+))?/$',
        GestaoContratoCRUDListView.as_view(),
        name='gestao_contrato',
    ),
    path(
        'visualizar_contrato_assinado/',
        ContratoAssinadoView.as_view(),
        name='visualizar_contrato_assinado'
    ),
    path(
        'cancelar_contrato/',
        CancelarContratoView.as_view(),
        name='cancelar_contrato'
    ),
    path(
        'minha_loja/dados_loja/',
        DadosLojaView.as_view(),
        name='dados_loja'
    ),
    path(
        'minha_loja/editar_dados_loja/',
        EditarDadosLojaView.as_view(),
        name='editar_dados_loja'
    ),
    path(
        'minha_loja/deletar_loja/',
        DeletarLojaView.as_view(),
        name='deletar_loja'
    ),
    path(
        'minha_loja/admins/criar_admin/',
        CriarAdminView.as_view(),
        name='criar_admin'
    ),
    path(
        'minha_loja/admins/',
        ListAdminsView.as_view(),
        name='admin_list'
    ),
    path(
        'minha_loja/admins/admin_detail/<int:pk>/',
        CardAdminView.as_view(),
        name='admin_detail'
    ),
    path(
        'minha_loja/admins/desativar_funcionario/',
        DesativarAdminView.as_view(),
        name='desativar_funcionario'
    ),
    path(
        'minha_loja/admins/reativar_funcionario/',
        ReativarAdminView.as_view(),
        name='reativar_funcionario'
    ),
    path(
        'minha_loja/admins/adicionar_papel/<int:group>/<int:funcionario>/',
        AdicionarPapelFuncionarioView.as_view(),
        name='adicionar_papel'
    ),
    path(
        'minha_loja/admins/remover_papel/<int:group>/<int:funcionario>/',
        RemoverPapelFuncionarioView.as_view(),
        name='remover_papel'
    ),
    path(
        'minha_loja/admins/adicionar_papel/',
        AdicionarPapelFuncionarioView.as_view(),
        name='adicionar_papel'
    ),
    path(
        'minha_loja/admins/remover_papel/',
        RemoverPapelFuncionarioView.as_view(),
        name='remover_papel'
    ),
    path(
        'minha_loja/admins/change_is_admin/',
        TrocarIsAdminFuncionarioView.as_view(),
        name='change_is_admin'
    ),
    path(
        'minha_loja/',
        InformacoesLojaView.as_view(),
        name='informacoes_loja'
    ),
]
