# Generated by Django 5.0.4 on 2024-05-24 22:09

import django.db.models.deletion
import saas.models.usuario_contratacao
import scope_auth.models.user_per_scope
import util.models.singleton
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioContratacao',
            fields=[
                (
                    'usuariogenerico_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=('common.usuariogenericopessoajuridica',),
            managers=[
                (
                    'usuarios',
                    saas.models.usuario_contratacao.UsuarioContratacaoManager(),
                ),
                ('users', scope_auth.models.user_per_scope.UserPerScopeManager()),
            ],
        ),
        migrations.CreateModel(
            name='GerenteDeContratos',
            fields=[
                (
                    'usuariocontratacao_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='saas.usuariocontratacao',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=('saas.usuariocontratacao', models.Model),
            managers=[
                (
                    'gerentes',
                    saas.models.usuario_contratacao.GerenteDeContratosManager(),
                ),
                (
                    'usuarios',
                    saas.models.usuario_contratacao.UsuarioContratacaoManager(),
                ),
                ('users', scope_auth.models.user_per_scope.UserPerScopeManager()),
                ('single_instance', util.models.singleton.SingletonManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClienteContratante',
            fields=[
                (
                    'usuariocontratacao_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='saas.usuariocontratacao',
                    ),
                ),
                (
                    'loja',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='contratante',
                        to='loja.loja',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=('saas.usuariocontratacao',),
            managers=[
                (
                    'contratantes',
                    saas.models.usuario_contratacao.ClienteContratanteManager(),
                ),
                (
                    'usuarios',
                    saas.models.usuario_contratacao.UsuarioContratacaoManager(),
                ),
                ('users', scope_auth.models.user_per_scope.UserPerScopeManager()),
            ],
        ),
    ]
