# Generated by Django 5.0.4 on 2024-05-26 19:21

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('padrao', models.BooleanField(default=False, verbose_name='Padrão')),
                (
                    'numero',
                    models.PositiveBigIntegerField(
                        editable=False, verbose_name='Numero'
                    ),
                ),
                (
                    'codigo',
                    models.PositiveIntegerField(editable=False, verbose_name='Codigo'),
                ),
                (
                    'bandeira',
                    models.PositiveIntegerField(
                        blank=True, editable=False, verbose_name='Bandeira'
                    ),
                ),
                (
                    'nome_titular',
                    models.CharField(
                        editable=False, max_length=200, verbose_name='Nome do titular'
                    ),
                ),
                (
                    'contratante',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='common.usuariogenericopessoajuridica',
                        verbose_name='Cliente Contratante',
                    ),
                ),
                (
                    'endereco',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='common.endereco',
                        verbose_name='Endereço do titular',
                    ),
                ),
            ],
            managers=[
                ('cartoes', django.db.models.manager.Manager()),
            ],
        ),
    ]
