# Generated by Django 5.0.4 on 2024-05-25 00:29

from django.db import migrations

from common.default_data.dados_empresa import *


def criar_gerente_de_contratos(apps, schema_editor):
    GerenteDeContratos = apps.get_model('saas', 'GerenteDeContratos')
    GerenteDeContratos.gerentes.criar_usuario_contratacao(
        cnpj=CNPJ, password=DEFAULT_PASSWORD, email=EMAIL, telefone=TELEFONE,
        razao_social=RAZAO_SOCIAL, nome_fantasia=NOME_FANTASIA
    )


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_grupos_usuarios_contrato'),
    ]

    operations = []
