# Generated by Django 5.0.4 on 2024-05-25 00:29

from django.db import migrations

from common.data import DadosEmpresa


def criar_gerente_de_contratos(apps, schema_editor):
    DefaultScope = apps.get_model('scope_auth', 'DefaultScope')
    PessoaUsuario = apps.get_model('common', 'PessoaUsuario')
    GerenteDeContratos = apps.get_model('saas', 'GerenteDeContratos')

    scope = DefaultScope.scopes.create()

    pessoa_usuario = PessoaUsuario.objects.create(
        codigo_pessoa=DadosEmpresa.CNPJ,
        scope=scope
    )

    from saas.models import GerenteDeContratos as _GerenteDeContratos
    setattr(GerenteDeContratos, 'USERNAME_FIELD',
            getattr(_GerenteDeContratos, 'USERNAME_FIELD'))

    gerente_de_contratos = GerenteDeContratos.gerente._create_user(
        username=pessoa_usuario,
        password=DadosEmpresa.SENHA_DEFAULT,
        email=DadosEmpresa.EMAIL,
        telefone=DadosEmpresa.TELEFONE,
        is_staff=True,
        codigo=DadosEmpresa.CNPJ,
        razao_social=DadosEmpresa.RAZAO_SOCIAL,
        nome_fantasia=DadosEmpresa.NOME_FANTASIA
    )

    Group = apps.get_model('auth', 'Group')

    gerente_de_contratos.groups.set([
        Group.objects.get(name='saas_gerente_de_contratos')
    ])


def deletar_gerente_de_contratos(apps, schema_editor):
    GerenteDeContratos = apps.get_model('saas', 'GerenteDeContratos')
    GerenteDeContratos.gerente.first().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_grupos_usuarios_contrato'),
    ]

    operations = [
        migrations.RunPython(criar_gerente_de_contratos, deletar_gerente_de_contratos),
    ]
