# Generated by Django 5.0.4 on 2024-10-21 11:05

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0003_gerente_de_contratos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'descricao',
                    models.CharField(
                        blank=True, max_length=100, verbose_name='Descrição'
                    ),
                ),
            ],
            managers=[
                ('pessoas', django.db.models.manager.Manager()),
            ],
        ),
    ]
