# Generated by Django 5.0.4 on 2024-12-14 01:38

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import util.mixins.not_updatable_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_periodo'),
        ('saas', '0003_gerente_de_contratos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'payment_method_id',
                    models.CharField(
                        max_length=248, unique=True, verbose_name='ID do pagamento'
                    ),
                ),
                (
                    'bandeira',
                    models.IntegerField(
                        choices=[(4, 'Visa'), (2, 'Mastercard')],
                        verbose_name='Bandeira',
                    ),
                ),
                (
                    'mes_validade',
                    models.PositiveSmallIntegerField(verbose_name='Mês de validade'),
                ),
                (
                    'ano_validade',
                    models.PositiveSmallIntegerField(verbose_name='Ano de validade'),
                ),
                (
                    'nome_titular',
                    models.CharField(max_length=200, verbose_name='Nome do titular'),
                ),
                ('numero', models.CharField(max_length=4, verbose_name='Numero')),
                ('padrao', models.BooleanField(default=False, verbose_name='Padrão')),
                (
                    'cliente_contratante',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cartoes',
                        to='saas.clientecontratante',
                        verbose_name='Cliente Contratante',
                    ),
                ),
                (
                    'endereco',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='common.endereco',
                        verbose_name='Endereço do titular',
                    ),
                ),
            ],
            bases=(
                util.mixins.not_updatable_fields.NotUpdatableFieldMixin,
                models.Model,
            ),
            managers=[
                ('cartoes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'descricao',
                    models.CharField(
                        blank=True, max_length=512, verbose_name='Descrição'
                    ),
                ),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                (
                    'valor_por_periodo',
                    models.DecimalField(
                        decimal_places=2, max_digits=11, verbose_name='Valor por perido'
                    ),
                ),
                (
                    'telas_simultaneas',
                    models.IntegerField(null=True, verbose_name='Telas simulteneas'),
                ),
                (
                    'taxa_de_multa',
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                100, 'Porcentagem não pode exceder 100%.'
                            ),
                            django.core.validators.MinValueValidator(
                                0, 'Porcentagem não pode ser negativo.'
                            ),
                        ],
                        verbose_name='Taxa de multa',
                    ),
                ),
                (
                    'tempo_maximo_de_atraso_em_dias',
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, 'Tempo não pode ser negativo.'
                            )
                        ],
                        verbose_name='Tempo máximo de atraso em dias',
                    ),
                ),
                (
                    'valor_total',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=11,
                        verbose_name='Valor Total',
                    ),
                ),
                (
                    'periodo',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to='common.periodo',
                        verbose_name='Periodo do contrato',
                    ),
                ),
            ],
            managers=[
                ('contratos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ContratoAssinado',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'vigente',
                    models.BooleanField(
                        default=False, verbose_name='Assinatura vigente'
                    ),
                ),
                (
                    'data_contratacao',
                    models.DateField(
                        auto_now_add=True, verbose_name='Data da contratação'
                    ),
                ),
                (
                    'cliente_contratante',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to='saas.clientecontratante',
                    ),
                ),
                (
                    'contrato',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to='saas.contrato'
                    ),
                ),
            ],
        ),
    ]
