# Generated by Django 5.0.4 on 2024-11-11 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0004_cartao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='contratante',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='saas.clientecontratante',
                verbose_name='Cliente Contratante',
            ),
        ),
    ]
