# Generated by Django 5.0.4 on 2024-12-08 14:46

import django.db.models.deletion
import django.db.models.manager
import util.mixins.model_call_full_clean
import util.mixins.not_updatable_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_periodo'),
        ('saas', '0005_alter_cartao_contratante_contrato_contratoassinado'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientecontratante',
            name='customer_id',
            field=models.CharField(blank=True, max_length=248, null=True),
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                (
                    'payment_id',
                    models.CharField(
                        max_length=248,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID do pagamento',
                    ),
                ),
                (
                    'descricao',
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name='Descrição'
                    ),
                ),
                (
                    'bandeira',
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, 'Visa'),
                            (2, 'Mastercard'),
                            (4, 'American Express'),
                            (5, 'Hipercard'),
                        ],
                        editable=False,
                        verbose_name='Bandeira',
                    ),
                ),
                (
                    'mes_validade',
                    models.PositiveSmallIntegerField(
                        editable=False, verbose_name='Mês de validade'
                    ),
                ),
                (
                    'ano_validade',
                    models.PositiveSmallIntegerField(
                        editable=False, verbose_name='Ano de validade'
                    ),
                ),
                (
                    'nome_titular',
                    models.CharField(max_length=200, verbose_name='Nome do titular'),
                ),
                ('padrao', models.BooleanField(default=False, verbose_name='Padrão')),
                (
                    'numero',
                    models.CharField(
                        editable=False, max_length=4, verbose_name='Numero'
                    ),
                ),
                (
                    'cliente_contratante',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='saas.clientecontratante',
                        verbose_name='Cliente Contratante',
                    ),
                ),
                (
                    'endereco',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='common.endereco',
                        verbose_name='Endereço do titular',
                    ),
                ),
            ],
            bases=(
                util.mixins.not_updatable_fields.NotUpdatableFieldMixin,
                util.mixins.model_call_full_clean.ValidateModelMixin,
                models.Model,
            ),
            managers=[
                ('cartoes', django.db.models.manager.Manager()),
            ],
        ),
    ]
