# Generated by Django 5.0.4 on 2024-11-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0006_contrato_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='valor_total',
        ),
    ]
