# Generated by Django 5.0.4 on 2024-11-17 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0006_contratoassinado'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contratoassinado',
            managers=[],
        ),
    ]
