# Generated by Django 5.0.4 on 2024-12-08 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0006_clientecontratante_customer_id_cartao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartao',
        ),
    ]
