# Generated by Django 5.0.4 on 2024-12-12 01:54

import django.db.models.deletion
import django.db.models.manager
import util.mixins.not_updatable_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_periodo'),
        ('saas', '0007_delete_cartao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'payment_method_id',
                    models.CharField(
                        max_length=248, unique=True, verbose_name='ID do pagamento'
                    ),
                ),
                (
                    'bandeira',
                    models.IntegerField(
                        choices=[(1, 'Visa'), (2, 'Mastercard')],
                        verbose_name='Bandeira',
                    ),
                ),
                (
                    'mes_validade',
                    models.PositiveSmallIntegerField(verbose_name='Mês de validade'),
                ),
                (
                    'ano_validade',
                    models.PositiveSmallIntegerField(verbose_name='Ano de validade'),
                ),
                (
                    'nome_titular',
                    models.CharField(max_length=200, verbose_name='Nome do titular'),
                ),
                ('numero', models.CharField(max_length=4, verbose_name='Numero')),
                ('padrao', models.BooleanField(default=False, verbose_name='Padrão')),
                (
                    'clente_contratante',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='saas.clientecontratante',
                        verbose_name='Cliente Contratante',
                    ),
                ),
                (
                    'endereco',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='common.endereco',
                        verbose_name='Endereço do titular',
                    ),
                ),
            ],
            bases=(
                util.mixins.not_updatable_fields.NotUpdatableFieldMixin,
                models.Model,
            ),
            managers=[
                ('cartoes', django.db.models.manager.Manager()),
            ],
        ),
    ]
