# Generated by Django 5.0.4 on 2024-12-12 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0008_cartao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartao',
            old_name='clente_contratante',
            new_name='cliente_contratante',
        ),
    ]
