# Generated by Django 5.0.4 on 2024-05-30 04:40

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                (
                    'scope',
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
            ],
            managers=[
                ('scopes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DefaultScope',
            fields=[
                (
                    '_singleton',
                    models.SmallIntegerField(
                        choices=[(1, 'single')], default=1, editable=False, unique=True
                    ),
                ),
                (
                    'base_scope',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name='default_scope',
                        serialize=False,
                        to='scope_auth.scope',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=('scope_auth.scope', models.Model),
            managers=[
                ('scopes', django.db.models.manager.Manager()),
            ],
        ),
    ]
