# Generated by Django 5.0.4 on 2024-05-24 17:46

from django.db import migrations


groupos_funcionarios = [
    'loja_chefes',
    'loja_gerentes_de_rh',
    'loja_gerentes_de_estoque',
    'loja_gerentes_de_vendas',
    'loja_caixeiros',
    'loja_vendedores'
]


def criar_grupos_funcionarios(apps, schema_editor):
    # TODO: Associar permissões aos grupos criados
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(name=g) for g in groupos_funcionarios
    ])


def deletar_grupos_funcionarios(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=groupos_funcionarios
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(criar_grupos_funcionarios, deletar_grupos_funcionarios)
    ]
