# Generated by Django 5.0.4 on 2024-11-21 02:51

from django.db import migrations

from common.grupos_create_delete import criar_grupos_usuarios, deletar_grupos_usuarios


# TODO: Associar permissões aos grupos criados
grupos_funcionarios = {
    'loja_gerentes_de_rh': [
        'is_gerente_de_rh',
        'gerir_funcionarios',
        'gerir_vendedores',
    ],
    'loja_gerentes_de_estoque': [
        'is_gerente_de_estoque',
    ],
    'loja_gerentes_financeiros': [
        'is_gerente_financeiro',
    ],
    'loja_caixeiros': [
        'is_caixeiro',
    ],
    'loja_vendedores': [
        'is_vendedor',
    ],
}


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: criar_grupos_usuarios(
                apps, schema_editor, grupos_funcionarios, 'loja'
            ),
            lambda apps, schema_editor: deletar_grupos_usuarios(
                apps, schema_editor, grupos_funcionarios, 'loja'
            ),
        )
    ]
