# Generated by Django 5.0.4 on 2024-11-24 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_grupos_funcionarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlice',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('numero_identificacao', models.CharField(max_length=50, unique=True)),
                ('horario_aberto', models.DateTimeField(blank=True, null=True)),
                ('dinheiro_em_caixa', models.FloatField(default=0.0)),
                ('ativo', models.BooleanField(default=False)),
                (
                    'loja',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='caixas',
                        to='loja.loja',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='FluxoDeCaixa',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('horario_aberto', models.DateTimeField()),
                ('horario_fechado', models.DateTimeField()),
                ('valor_em_caixa', models.FloatField()),
                (
                    'caixa',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='fluxos',
                        to='loja.caixa',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TrabalhoPorDia',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('dia_da_semana', models.IntegerField()),
                (
                    'timeslices',
                    models.ManyToManyField(
                        related_name='dias_de_trabalho', to='loja.timeslice'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TrabalhaCaixa',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'caixa',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='trabalhos',
                        to='loja.caixa',
                    ),
                ),
                (
                    'caixeiro',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='trabalhos',
                        to='loja.caixeiro',
                    ),
                ),
                (
                    'trabalho_por_dia',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='trabalhos',
                        to='loja.trabalhopordia',
                    ),
                ),
            ],
        ),
    ]
