# Generated by Django 5.0.4 on 2024-11-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_timeslice_caixa_fluxodecaixa_trabalhopordia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caixa',
            options={'permissions': [('manage_caixa', 'Pode gerenciar caixas')]},
        ),
    ]
