# Generated by Django 5.0.4 on 2024-11-30 14:56

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_caixa_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='caixa',
            managers=[
                ('caixas', django.db.models.manager.Manager()),
            ],
        ),
    ]
