# Generated by Django 5.0.4 on 2024-12-05 18:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_produto_produtoporlote_promocao'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='caixa',
            managers=[],
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_de_barras',
            field=models.CharField(
                blank=True, max_length=128, verbose_name='Código de barras'
            ),
        ),
        migrations.AddField(
            model_name='produto',
            name='em_venda',
            field=models.BooleanField(default=False, verbose_name='À venda'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_de_venda',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=11,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, 'Preço não pode ser nulo ou negativo.'
                    )
                ],
                verbose_name='Preço de venda',
            ),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='data_inicio',
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.date(2024, 12, 5),
                        'A data de início não pode ser no passado.',
                    )
                ],
                verbose_name='Data de início',
            ),
        ),
    ]
