# Generated by Django 5.0.4 on 2024-12-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_caixa_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='caixa',
            managers=[],
        ),
        migrations.AlterField(
            model_name='caixa',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
