# Generated by Django 5.0.4 on 2024-12-05 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_alter_caixa_managers_produto_codigo_de_barras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxodecaixa',
            name='funcionario',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='fluxos',
                to='loja.funcionario',
            ),
        ),
    ]
