# Generated by Django 5.0.4 on 2024-05-08 23:21

import common.models.escopo
import common.models.usuario_generico
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoEscopoPair',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('codigo', models.CharField(max_length=14, verbose_name='CPF ou CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='Escopo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'nome',
                    models.CharField(
                        blank=True, max_length=150, verbose_name='First name'
                    ),
                ),
                (
                    'sobrenome',
                    models.CharField(
                        blank=True, max_length=150, verbose_name='Last name'
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        blank=True, max_length=254, verbose_name='Endereço de email'
                    ),
                ),
                (
                    'data_nascimento',
                    models.DateField(
                        blank=True, null=True, verbose_name='Data de nascimento'
                    ),
                ),
                (
                    'telefone',
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name='Telefone'
                    ),
                ),
                (
                    'codigo_escopo_pair',
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='common.codigoescopopair',
                        verbose_name='ID do pair de código e escopo',
                    ),
                ),
            ],
            managers=[
                ('pessoas', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EscopoContratacao',
            fields=[
                (
                    'escopo_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='common.escopo',
                    ),
                ),
                (
                    '_singleton',
                    models.BooleanField(default=True, editable=False, unique=True),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=('common.escopo', models.Model),
            managers=[
                ('escopo_contratacao', common.models.escopo.EscopoContratacaoManager()),
            ],
        ),
        migrations.AddField(
            model_name='codigoescopopair',
            name='escopo',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='common.escopo'
            ),
        ),
        migrations.CreateModel(
            name='UsuarioGenerico',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                (
                    'last_login',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='last login'
                    ),
                ),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False,
                        help_text='Designates that this user has all permissions without explicitly assigning them.',
                        verbose_name='superuser status',
                    ),
                ),
                (
                    'is_staff',
                    models.BooleanField(
                        default=False,
                        help_text='Designates whether the user can log into this admin site.',
                        verbose_name='staff status',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                        verbose_name='active',
                    ),
                ),
                (
                    'date_joined',
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name='date joined'
                    ),
                ),
                (
                    'pessoa',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name='usuario',
                        serialize=False,
                        to='common.pessoa',
                    ),
                ),
                (
                    'groups',
                    models.ManyToManyField(
                        blank=True,
                        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.group',
                        verbose_name='groups',
                    ),
                ),
                (
                    'user_permissions',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Specific permissions for this user.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.permission',
                        verbose_name='user permissions',
                    ),
                ),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('common.pessoa', models.Model),
            managers=[
                ('usuarios', common.models.usuario_generico.UsuarioGenericoManager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='codigoescopopair',
            unique_together={('codigo', 'escopo')},
        ),
    ]
