# Generated by Django 5.0.4 on 2024-05-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'cep',
                    models.CharField(editable=False, max_length=8, verbose_name='CEP'),
                ),
                ('numero', models.PositiveIntegerField(verbose_name='Numero')),
                (
                    'complemento',
                    models.CharField(blank=True, verbose_name='Complemento'),
                ),
            ],
        ),
    ]
