# Generated by Django 5.0.4 on 2024-05-28 17:40

import common.models.endereco
import common.validators
import django.db.models.manager
import util.mixins.model_call_full_clean
import util.mixins.not_updatable_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'cep',
                    models.CharField(
                        max_length=8,
                        validators=[
                            common.validators.CEPValidator(
                                common.models.endereco.EnderecoManager.get_installed_cep_providers
                            )
                        ],
                        verbose_name='CEP',
                    ),
                ),
                ('numero', models.PositiveIntegerField(verbose_name='Numero')),
                (
                    'complemento',
                    models.CharField(blank=True, verbose_name='Complemento'),
                ),
            ],
            bases=(
                util.mixins.not_updatable_fields.NotUpdatableFieldMixin,
                util.mixins.model_call_full_clean.ValidateModelMixin,
                models.Model,
            ),
            managers=[
                ('enderecos', django.db.models.manager.Manager()),
            ],
        ),
    ]
