# Generated by Django 5.0.4 on 2024-05-09 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_escopo_de_contratacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='codigo_escopo_pair',
            new_name='username',
        ),
    ]
