# Generated by Django 5.0.4 on 2024-10-29 03:22

import django.core.validators
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'numero_de_periodos',
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, 'Numero de  não pode ser negativo.'
                            )
                        ],
                        verbose_name='Numero de periodos',
                    ),
                ),
                (
                    'unidades_de_tempo_por_periodo',
                    models.CharField(
                        choices=[('ANO', 'Ano'), ('MES', 'Mes'), ('DIA', 'Dia')],
                        default='MES',
                        max_length=3,
                        verbose_name='Unidade de tempo por periodo',
                    ),
                ),
            ],
            managers=[
                ('periodos', django.db.models.manager.Manager()),
            ],
        ),
    ]
